"""add brief cache fields

Revision ID: 8f5ce6213f10
Revises: a10f70fbec6d
Create Date: 2026-03-07 00:52:39.022503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f5ce6213f10'
down_revision: Union[str, Sequence[str], None] = 'a10f70fbec6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('brief_text', sa.Text(), nullable=True))
    op.add_column('event', sa.Column('brief_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'brief_generated_at')
    op.drop_column('event', 'brief_text')
    # ### end Alembic commands ###
