"""add satellite fields

Revision ID: a10f70fbec6d
Revises: ae3cc52e1529
Create Date: 2026-03-06 21:58:26.340575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a10f70fbec6d'
down_revision: Union[str, Sequence[str], None] = 'ae3cc52e1529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('satellite_coverage', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('event', sa.Column('next_opportunities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'next_opportunities')
    op.drop_column('event', 'satellite_coverage')
    # ### end Alembic commands ###
