"""initial schema

Revision ID: ae3cc52e1529
Revises: 
Create Date: 2026-03-06 01:03:08.140065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae3cc52e1529'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('first_detection_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.Enum('STRIKE', 'MISSILE', 'DRONE', 'NAVAL', 'TROOP', name='eventtype'), nullable=False),
    sa.Column('confidence', sa.Enum('VERIFIED', 'LIKELY', 'REPORTED', 'UNCONFIRMED', 'DISPUTED', name='confidencelevel'), nullable=True),
    sa.Column('cluster_radius_km', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_category', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('VERIFIED', 'UNVERIFIED', 'DISPUTED', 'DISPROVEN', 'COORDINATED_MESSAGING_SUSPECTED', name='claimstatus'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_category', sa.Enum('WESTERN', 'RUSSIAN', 'MIDDLE_EAST', 'OSINT', 'LOCAL', name='sourcecategory'), nullable=False),
    sa.Column('article_url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('coordinates_mentioned', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('narrative_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_before', sa.String(), nullable=False),
    sa.Column('status_after', sa.String(), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('narrative_history')
    op.drop_table('signals')
    op.drop_table('claims')
    op.drop_table('event')
    # ### end Alembic commands ###
